services:
  empresa-aerea-pg16:
    image: postgres:16-alpine
    container_name: dac-pg16
    hostname: dac-pg16
    volumes:
      - empresa-aerea-pg:/var/lib/postgresql/data
      - /Repositorios DAC/TrabalhoFinalDAC/postgresql/init.sql:/tmp/init.sql
      - /Repositorios DAC/TrabalhoFinalDAC/postgresql/docker-entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh
    ports:
      - "30001:5432"
    environment:
      DBPOSTGRES: dacdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "admin"
    networks:
      - dac-net

  empresa-aerea-mongo:
    image: mongo
    container_name: dac-mongo
    hostname: dac-mongo 
    environment:
      MONGO_INITDB_ROOT_USERNAME: admdac
      MONGO_INITDB_ROOT_PASSWORD: "dacsecret"
    ports:
      - "30002:27017"
    volumes:
      - empresa-aerea-mongo:/data/db
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - dac-net

  empresa-aerea-java:
    image: openjdk:17-jdk-slim  # Ou uma imagem personalizada que você tenha
    container_name: empresa-aerea-java
    build: 
      context: ./backend  # Substitua pelo caminho correto
      dockerfile: Dockerfile  # Se você tiver um Dockerfile
    ports:
      - "8088:8080"  # Ou outra porta que sua aplicação use
 
volumes:
  empresa-aerea-pg:
    driver: local
    name: empresa-aerea-pg
  empresa-aerea-mongo:
    driver: local
    name: empresa-aerea-mongo 
  empresa-aerea-java:
    driver: local
    name: empresa-aerea-java


networks:
  dac-net:
    name: "dac-net"
