version: '3.5'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: dac-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    volumes:
      - dac-mongodb-volume:/data/db
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - dac-net

networks:
  dac-net:
    name: dac-net
    external: true

volumes:
  dac-mongodb-volume:
    driver: local
    name: dac-mongodb-volume