services:
  postgres:
    image: postgres:16-alpine
    container_name: dac-postgres
    ports:
      - 30000:5432
    volumes:
      - dac-postgres-volume:/var/lib/postgresql/data
      - ./postgresql/init.sql:/tmp/init.sql
      - ./postgresql/docker-entrypoint.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      DBPOSTGRES: dacdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - dac-net

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 30001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - dac-postgres-volume:/var/lib/postgresql/data
    networks:
      - dac-net

networks:
  dac-net:
    name: dac-net
    external: true

volumes:
  dac-postgres-volume:
    driver: local
    name: dac-postgres-volume
