services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - dac-rabbitmq-volume:/var/lib/rabbitmq/
    networks:
        - dac-net

networks:
  dac-net:
    driver: bridge

volumes:
  dac-rabbitmq-volume:
    driver: local
    name: dac-rabbitmq-volume