package br.ufpr.dac.ms_orchestrator.rabbitmq.config;

public class RabbitMQConstants {
  public static final String FILA_CLIENTE_CRIADO = "CLIENTE_CRIADO";
  public static final String FILA_CRIAR_USUARIO_CLIENTE = "CRIAR_USUARIO_CLIENTE";

  public static final String FILA_FUNCIONARIO_CRIADO = "FUNCIONARIO_CRIADO";
  public static final String FILA_CRIAR_USUARIO_FUNCIONARIO = "CRIAR_USUARIO_FUNCIONARIO";

  public static final String FILA_CANCELAR_RESERVA_READ = "CANCELAR_RESERVA_READ";
  public static final String FILA_CHECKIN_RESERVA_READ = "CHECKIN_RESERVA_READ";

  public static final String FILA_REEMBOLSAR_MILHAS_RESERVA = "REEMBOLSAR_MILHAS_RESERVA";
  public static final String FILA_REEMBOLSAR_TRANSACAO = "REEMBOLSAR_TRANSACAO";
  public static final String FILA_RETIRAR_TRANSACAO = "RETIRAR_TRANSACAO";

  public static final String FILA_REALIZAR_RESERVA_READ = "REALIZAR_RESERVA_READ";
  public static final String FILA_RETIRAR_MILHAS_RESERVA = "RETIRAR_MILHAS_RESERVA";

  public static final String FILA_SOLICITAR_USUARIO_CLIENTE = "SOLICITAR_USUARIO_CLIENTE";
  public static final String FILA_USUARIO_CLIENTE_CRIADO = "USUARIO_CLIENTE_CRIADO";
  public static final String FILA_RETORNAR_USUARIO_CLIENTE = "RETORNAR_CLIENTE_USUARIO";
  
  public static final String FILA_VOO_REALIZADO = "VOO_REALIZADO";
  public static final String FILA_RESERVAS_REALIZADO = "RESERVAS_REALIZADO_VOO";
  public static final String FILA_VOO_CANCELADO = "VOO_CANCELADO";
  public static final String FILA_RESERVAS_CANCELADO = "RESERVAS_CANCELADO_VOO";

  public static final String[] TODAS_FILAS = {
    FILA_CLIENTE_CRIADO, FILA_CRIAR_USUARIO_CLIENTE, FILA_FUNCIONARIO_CRIADO, FILA_CRIAR_USUARIO_FUNCIONARIO, FILA_CANCELAR_RESERVA_READ, FILA_CHECKIN_RESERVA_READ,
    FILA_REEMBOLSAR_MILHAS_RESERVA, FILA_REEMBOLSAR_TRANSACAO, FILA_REALIZAR_RESERVA_READ, FILA_RETIRAR_MILHAS_RESERVA, FILA_RETIRAR_TRANSACAO,
    FILA_SOLICITAR_USUARIO_CLIENTE, FILA_USUARIO_CLIENTE_CRIADO, FILA_RETORNAR_USUARIO_CLIENTE, FILA_CLIENTE_CRIADO, FILA_VOO_REALIZADO, FILA_VOO_CANCELADO,
    FILA_RESERVAS_REALIZADO, FILA_RESERVAS_CANCELADO
  };
}
